sudo: required
services:
  - docker

before_install:
  - docker build -t vghildiyal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vghildiyal/react-test npm run test 

after_success:
  - docker build -t vghildiyal/multi-client ./client
  - docker build -t vghildiyal/multi-nginx ./nginx
  - docker build -t vghildiyal/multi-server ./server
  - docker build -t vghildiyal/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vghildiyal/multi-client
  - docker push vghildiyal/multi-nginx
  - docker push vghildiyal/multi-server
  - docker push vghildiyal/multi-worker

deploy :
  provider : elasticbeanstalk
  region : ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-801391952744
  bucket_path: docker-multi
  on :
    branch: master
  access_key_id : 
    secure: $ACCESS_KEY
  secret_access_key : 
    secure: $SECRET_KEY